---
- name: Configure BGP on Juniper Routers
  hosts: juniper
  connection: local
  gather_facts: no  
  vars_files:
    - configuration_variables.yml

  vars_prompt:
    - name: ansible_user
      prompt: "Enter the username"
      private: no
    - name: ansible_password
      prompt: "Enter the password"
      private: yes
  
  vars:
    host: "{{ inventory_hostname }}"
    user: " {{ ansible_user }}"
    passwd: "{{ ansible_password }}"
  
  tasks:
    - name: Configure BGP groups and neighbors using set commands
      juniper.device.config:
        lines:
          # Set the local ASN
          - set routing-options autonomous-system {{ item.local_asn }}
          # Configure each BGP group
          {% for group in item.bgp_groups %}
          - set protocols bgp group {{ group.name }} type external
          {% for neighbor in group.neighbors %}
          - set protocols bgp group {{ group.name }} neighbor {{ neighbor.ip }} peer-as {{ neighbor.peer_as }}
          {% endfor %}
          {% endfor %}
          # Add static routes
          {% for network in item.networks %}
          - set routing-options static route {{ network }} next-hop discard
          {% endfor %}
        format: set
        commit: no
      loop: "{{ bgp_config }}"
      loop_control:
        label: "{{ item.site }}"

