---
- name: Configure BGP on Juniper Routers
  hosts: juniper
  connection: local
  gather_facts: no  
  vars_files:
    - configuration_variables.yml

  vars_prompt:
    - name: ansible_user
      prompt: "Enter the username"
      private: no
    - name: ansible_password
      prompt: "Enter the password"
      private: yes
  
  vars:
    host: "{{ inventory_hostname }}"
    user: " {{ ansible_user }}"
    passwd: "{{ ansible_password }}"
  
  tasks:
    - name: Generate JSON configuration for BGP
      copy:
        content: "{{ bgp_config_json }}"
        dest: /tmp/bgp_config_{{ item.site }}.json
      loop: "{{ bgp_config }}"
      loop_control:
        label: "{{ item.site }}"

    - name: Load JSON configuration on each router
      juniper.device.config:
        host: "{{ inventory_hostname }}"
        user: your-username
        passwd: your-password
        src: /tmp/bgp_config_{{ item.site }}.json
        format: json
        commit: yes
      loop: "{{ bgp_config }}"
      loop_control:
        label: "{{ item.site }}"
