---
- name: Configure BGP on Juniper Routers
  hosts: juniper
  connection: local
  gather_facts: no  
  vars_files:
    - configuration_variables.yml

  vars_prompt:
    - name: ansible_user
      prompt: "Enter the username"
      private: no
    - name: ansible_password
      prompt: "Enter the password"
      private: yes
  
  vars:
    host: "{{ inventory_hostname }}"
    user: " {{ ansible_user }}"
    passwd: "{{ ansible_password }}"
  
  tasks:
    - name: Configure BGP for each site
      juniper.device.config:
        host: "{{ inventory_hostname }}"
        user: your-username
        passwd: your-password
        config:
          protocols:
            bgp:
              group: "{{ item.bgp_groups }}"
          routing-options:
            autonomous-system: "{{ item.local_asn }}"
        format: json
        commit: no
      loop: "{{ bgp_config }}"
      when: inventory_hostname in bgp_config | map(attribute='site') | list
