---
- name: Configure BGP on Juniper Routers
  hosts: juniper
  connection: local
  gather_facts: no
  vars_files:
    - configuration_variables.yml

  vars_prompt:
    - name: ansible_user
      prompt: "Enter the username"
      private: no
    - name: ansible_password
      prompt: "Enter the password"
      private: yes

  vars:
    host: "{{ inventory_hostname }}"
    user: "{{ ansible_user }}"
    passwd: "{{ ansible_password }}"

  tasks:
    - name: Generate BGP set commands dynamically for each router
      set_fact:
        bgp_commands: |
          [
            "set routing-options autonomous-system {{ site_config[inventory_hostname].local_asn }}",
            {% for group_name, group_data in site_config[inventory_hostname].bgp_groups.items() %}
              {% for neighbor in group_data.neighbors %}
                "set protocols bgp group {{ group_name }} neighbor 192.168.{{ '99' if group_name == 'cox' else '100' }}.{{ neighbor.ip_suffix }} peer-as {{ neighbor.asn }}",
              {% endfor %}
            {% endfor %}
          ]

    - name: Debug the generated BGP set commands
      debug:
        msg: "{{ bgp_commands }}"

    - name: Apply BGP set commands to the Juniper device
      juniper.device.config:
        lines: "{{ bgp_commands }}"
        format: set
        load: merge
        commit: no
        config_mode: dynamic
