---
- name: Configure BGP on Juniper Routers
  hosts: juniper
  connection: local
  gather_facts: no  
  vars_files:
    - configuration_variables.yml

  vars_prompt:
    - name: ansible_user
      prompt: "Enter the username"
      private: no
    - name: ansible_password
      prompt: "Enter the password"
      private: yes
  
  vars:
    host: "{{ inventory_hostname }}"
    user: " {{ ansible_user }}"
    passwd: "{{ ansible_password }}"
  
  tasks:
    - name: Generate set commands for BGP configuration
      set_fact:
        bgp_set_commands: >-
          {{
            [
              "set routing-options autonomous-system {{ item.local_asn }}",
              {% for group in item.bgp_groups %}
              "set protocols bgp group {{ group.name }} type external",
              {% for neighbor in group.neighbors %}
              "set protocols bgp group {{ group.name }} neighbor {{ neighbor.ip }} peer-as {{ neighbor.peer_as }}",
              {% endfor %}
              {% endfor %}
              {% for network in item.networks %}
              "set routing-options static route {{ network }} next-hop discard"
              {% endfor %}
            ] | join('\n')
          }}
      loop: "{{ bgp_config }}"
      loop_control:
        label: "{{ item.site }}"

    - name: Apply set commands to the Juniper device
      juniper.device.config:
        lines: "{{ bgp_set_commands.split('\n') }}"
        format: set
        commit: no
      loop: "{{ bgp_config }}"
      loop_control:
        label: "{{ item.site }}"

