---
- name: Configure BGP on Juniper Routers
  hosts: juniper
  connection: local
  gather_facts: no  
  vars_files:
    - configuration_variables.yml

  vars_prompt:
    - name: ansible_user
      prompt: "Enter the username"
      private: no
    - name: ansible_password
      prompt: "Enter the password"
      private: yes
  
  vars:
    host: "{{ inventory_hostname }}"
    user: " {{ ansible_user }}"
    passwd: "{{ ansible_password }}"

tasks:
    - name: Configure BGP for each site
      juniper.device.config:
        host: "{{ inventory_hostname }}"
        config: |
          routing-options {
              autonomous-system {{ item.local_asn }};
          }
          protocols {
              bgp {
                  group {{ group.name }} {
                      type external;
                      neighbor {{ neighbor.ip }} {
                          peer-as {{ neighbor.asn }};
                      }
                  }
              }
          }
      with_items: "{{ bgp_config }}"
      loop_control:
        label: "{{ item.site }}"
      vars:
        groups: "{{ item.bgp_groups }}"
        neighbors: "{{ group.neighbors }}"
