bgp_config:
  - site: HQ
    local_asn: 65010
    bgp_groups:
      - name: "10.10-cox"
        neighbors:
          - ip: "192.168.99.11"
            peer_as: 65011
          - ip: "192.168.99.12"
            peer_as: 65012
          - ip: "192.168.99.70"
            peer_as: 65070
      - name: "10.10-lumen"
        neighbors:
          - ip: "192.168.100.11"
            peer_as: 65011
          - ip: "192.168.100.12"
            peer_as: 65012
          - ip: "192.168.100.70"
            peer_as: 65070
