bgp_config:
  - site: HQ
    local_asn: 65010
    networks:
      - "10.10.0.0/16"
    bgp_groups:
      - name: "10.10-cox"
        neighbors:
          - { ip: "192.168.99.11", asn: 65011 }
          - { ip: "192.168.99.12", asn: 65012 }
          - { ip: "192.168.99.70", asn: 65070 }
      - name: "10.10-lumen"
        neighbors:
          - { ip: "192.168.100.11", asn: 65011 }
          - { ip: "192.168.100.12", asn: 65012 }
          - { ip: "192.168.100.70", asn: 65070 }
